config/routes.rb
Rails.application.routes.draw do
  get '/activation/:token', to: 'users#account_activation', as: 'account_activation'
  get '/password_reset/:token', to: 'password_resets#new', as: 'reset_password'
  get '/merchant', to: 'merchant/coupons#new'

  post "/subscribe" => "subscriptions#create"

  resource :password_reset, only: [:create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :merchant_sessions, only: [:new, :create, :destroy]
  resource :password_request, only: [:new, :create]

  root 'deals#index'

  get "/signup", to: 'users#new'

  resource :users, only: [:create]

  resources :deals, only: [:index, :show] do
    collection do
      get 'search'
      get 'past'
    end
    member do
      get 'refresh'
    end
    resources :orders, only: [:new, :index, :edit, :update, :destroy, :show]
  end

  resources :merchants, only: [] do
    member do
      get 'deals'
    end
  end

  resources :categories, only: [] do
    member do
      get 'deals'
    end
  end

  get 'admin' => 'admin#index'

  namespace :api, defaults: { format: :json } do
    get '/orders/:token', to: 'orders#show'
  end

  namespace :merchant do
    resources :coupons, only: [:new] do
      collection do
        post 'redeem'
      end
    end
    resources :deals, only: [:index, :show]
  end

  namespace :admin do
    resources :deals do
      member do
        put 'publish'
        put 'unpublish'
      end
    end
    resources :reports, only: [] do
      collection do
        get 'merchants'
      end
    end
  end

  resources :orders do
    resources :charges, only: [:create]
  end

end

app/views/user_notifier/coupon_mail.html.erb
<p>
  Hello <%= @order.user.first_name %>,
</p>

Congratulations! The deal <%= @order.deal.title %> is through, and we are sending 5 coupons against the order <%= @order.id %>.

Your Coupon Codes are : 

<ul>
<%= render @order.coupons %>

</ul>


Please visit ordershow[link] for more details

app/views/user_notifier/coupon_mail.text.erb
<p>
  Hello <%= @order.user.first_name %>,
</p>

Congratulations! The deal <%= @order.deal.title %> is through, and we are sending 5 coupons against the order <%= @order.id %>.

Your Coupon Codes are : 

<ul>

</ul>


Please visit ordershow[link] for more details

app/views/user_notifier/password_reset_mail.html.erb
<p>
  Hello <%= @user.first_name %>,
</p>

You're receiving this email because you requested a password reset for the user <%= @user.email %> 

<%= link_to reset_password_url(@user.forgot_password_token), reset_password_url(@user.forgot_password_token) %>
This Link is valid till <%= @user.forgot_password_expire_at.to_formatted_s(:short) %> .

If you did not request your password to be reset, just ignore this email and your password will continue to stay the same.

app/views/user_notifier/password_reset_mail.text.erb
<p>
  Hello <%= @user.first_name %>,
</p>

You're receiving this email because you requested a password reset for the user <%= @user.email %> 

<%= link_to reset_password_url(@user.forgot_password_token), reset_password_url(@user.forgot_password_token) %>
This Link is valid till <%= @user.forgot_password_expire_at.to_formatted_s(:short) %> .

If you did not request your password to be reset, just ignore this email and your password will continue to stay the same.

app/views/user_notifier/refund_mail.html.erb
<p>
  Hello <%= @order.user.first_name %>,
</p>

Sorry! The deal <%= @order.deal.title %> is  not through, and we are refunding <%= @order.calculate_total_price %> against the order <%= @order.id %>.

Please visit ordershow[link] for more details

app/views/user_notifier/refund_mail.text.erb
<p>
  Hello <%= @order.user.first_name %>,
</p>

Sorry! The deal <%= @order.deal.title %> is  not through, and we are refunding <%= @order.calculate_total_price %> against the order <%= @order.id %>.

Please visit ordershow[link] for more details

app/views/user_notifier/registration_confirmation.html.erb
<p>
  Hi <%= @user.name %>,
</p>

Thanks for registering! To confirm your registration click the URL below. <br>

<%= link_to account_activation_url(@user.verification_token), account_activation_url(@user.verification_token) %>

app/views/user_notifier/registration_confirmation.text.erb
Hi <%= @user.name %>,

Thanks for registering! To confirm your registration click the URL below.

<%= link_to account_activation_url(@user.verification_token), account_activation_url(@user.verification_token) %>

app/views/user_notifier/verification_mail.html.erb
<p>
  Hi <%= @user.first_name %>,
</p>

Thanks for registering! To confirm your registration click the URL below. <br>

<%= link_to account_activation_url(@user.verification_token), account_activation_url(@user.verification_token) %>
This Link is valid till <%= @user.verification_token_expire_at.to_formatted_s(:short)%> .

app/views/user_notifier/verification_mail.text.erb
Hi <%= @user.first_name %>,

Thanks for registering! To confirm your registration click the URL below.

<%= link_to account_activation_url(@user.verification_token), account_activation_url(@user.verification_token) %>

This Link is valid till <%= @user.verification_token_expire_at.to_formatted_s(:short)%>.