config/routes.rb
Rails.application.routes.draw do
  get '/activation/:token', to: 'users#account_activation', as: 'account_activation'
  get '/password_reset/:token', to: 'password_resets#new', as: 'reset_password'
  get '/merchant', to: 'merchant/coupons#new'

  post "/subscribe" => "subscriptions#create"

  resource :password_reset, only: [:create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :merchant_sessions, only: [:new, :create, :destroy]
  resource :password_request, only: [:new, :create]

  root 'deals#index'

  get "/signup", to: 'users#new'

  resource :users, only: [:create]

  resources :deals, only: [:index, :show] do
    collection do
      get 'search'
      get 'past'
    end
    member do
      get 'refresh'
    end
    resources :orders, only: [:new, :index, :edit, :update, :destroy, :show]
  end

  resources :merchants, only: [] do
    member do
      get 'deals'
    end
  end

  resources :categories, only: [] do
    member do
      get 'deals'
    end
  end

  get 'admin' => 'admin#index'

  namespace :api, defaults: { format: :json } do
    get '/orders/:token', to: 'orders#show'
  end

  namespace :merchant do
    resources :coupons, only: [:new] do
      collection do
        post 'redeem'
      end
    end
    resources :deals, only: [:index, :show]
  end

  namespace :admin do
    resources :deals do
      member do
        put 'publish'
        put 'unpublish'
      end
    end
    resources :reports, only: [] do
      collection do
        get 'merchants'
      end
    end
  end

  resources :orders do
    resources :charges, only: [:create]
  end

end

app/models/deal.rb
# == Schema Information
#
# Table name: deals
#
#  id                   :integer          not null, primary key
#  title                :string(255)      not null
#  description          :text(65535)
#  min_qty              :integer
#  max_qty              :integer
#  start_time           :datetime
#  expire_time          :datetime
#  price                :decimal(8, 2)
#  max_qty_per_customer :integer
#  instructions         :text(65535)
#  publishable          :boolean          default(FALSE)
#  category_id          :integer          not null
#  merchant_id          :integer          not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  sold_quantity        :integer          default(0)
#  lock_version         :integer          default(0)
#  processed            :boolean          default(FALSE)
#  notified             :boolean          default(FALSE)
#
# Indexes
#
#  index_deals_on_category_id  (category_id)
#  index_deals_on_merchant_id  (merchant_id)
#
# Foreign Keys
#
#  fk_rails_6b084cd147  (category_id => categories.id)
#  fk_rails_bed9e08b8f  (merchant_id => merchants.id)
#

class Deal < ActiveRecord::Base
  DESCRIPTION_MIN_LENGTH = 10
  MINIMUM_PRICE = 0.01
  MINIMUM_MIN_QTY = 1
  MINIMUM_MAX_QTY_PER_CUSTOMER = 1


  self.per_page = 10

  validates :title, presence: true
  validates :category, presence: true
  validates :merchant, presence: true
  with_options if: "publishable?" do |deal|

    deal.validates :description, length: {
      minimum: DESCRIPTION_MIN_LENGTH,
      tokenizer: lambda { |str| str.split(/\s+/)},
      too_short: "must have at least #{ DESCRIPTION_MIN_LENGTH } words"
    }
    deal.validates :min_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: MINIMUM_MIN_QTY }
    deal.validates :sold_quantity, numericality: { only_integer: true, less_than_or_equal_to: ->(deal) { deal.max_qty } }, if: :max_qty?
    deal.validates :start_time, presence: true
    deal.validates :expire_time, presence: true
    deal.validates :price, presence: true, numericality: { greater_than_or_equal_to: MINIMUM_PRICE }
    deal.validates :instructions, presence: true
    deal.validates_associated :locations
    deal.validates_associated :deal_images
    deal.validates_with StartTimeValidator, unless: ->(deal) { deal.deal_processing? || deal.deal_was_notified? }
    deal.validates_with ExpireTimeValidator
    deal.validates_with ImageValidator
    deal.validates_with LocationValidator
  end
  validates :max_qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: ->(deal) { deal.min_qty } }, if: ("publishable? && min_qty?")
  validates :max_qty_per_customer, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: MINIMUM_MAX_QTY_PER_CUSTOMER, less_than_or_equal_to: ->(deal) { deal.max_qty }}, if: ("publishable? && max_qty? ")
  
  scope :published, -> { where(publishable: true) }
  scope :live, -> (time = Time.current){ published.where("start_time <= ?", time).where("? <= expire_time ", time) }
  scope :past, -> (time = Time.current){ published.where("? > expire_time", time) }
  scope :search, ->(keyword) { published.includes(:locations).where("lower(title) LIKE ? OR lower(locations.city) LIKE ?","%#{keyword.downcase}%", "%#{keyword.downcase}%" ).references(:locations)}
  scope :processed, -> { where(processed: true ) }
  scope :not_processed, -> { where.not(processed: true) }
  scope :for_coupon_processing, -> { past.not_processed.joins(:orders).group("orders.deal_id").having("sum(orders.quantity) >= deals.min_qty") }
  scope :for_refund_processing, -> { past.not_processed.joins(:orders).group("orders.deal_id").having("sum(orders.quantity) < deals.min_qty") }
  scope :successfully_expired, -> { past.processed.where('min_qty <= sold_quantity') }

  belongs_to :category
  belongs_to :merchant
  has_many :locations, dependent: :destroy, validate: false
  has_many :deal_images, dependent: :destroy, validate: false
  has_many :orders, dependent: :restrict_with_error
  has_many :coupons, through: :orders

  accepts_nested_attributes_for :deal_images, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :locations, allow_destroy: true, reject_if: :all_blank

  before_validation :check_if_deal_can_be_updated?, if: "publishable? && !deal_was_notified?", unless: :deal_processing?

  def publish
    update(publishable: true)
  end

  def unpublish
    update(publishable: false)
  end

  def live?
    start_time && Time.current.between?(start_time, expire_time)
  end

  def expired?
    expire_time && expire_time < Time.current
  end

  def sold_out?
    sold_quantity >= max_qty
  end

  def quantity_available
    max_qty - sold_quantity
  end

  def increase_sold_qty_by(quantity)
    updated_sold_quantity = sold_quantity + quantity
    update_attribute(:sold_quantity, updated_sold_quantity)
  end

  def remaining_quantity_to_activate
    min_qty - sold_quantity
  end

  def deal_processing?
    if changes
      processed_was == false && processed == true
    end
  end

  def deal_was_notified?
    if changes
      notified_was == false && notified == true
    end
  end

  private

  def check_if_deal_can_be_updated?
    if expired?
      errors[:base] << "Expired deal cannot be updated."
      false
    elsif live?
      errors[:base] << "Live Deals cannot be updated."
      false
    end
  end

end

app/controllers/admin/deals_controller.rb
class Admin::DealsController < Admin::BaseController

  before_action :set_deal, only: [:show, :edit, :destroy, :update, :publish, :unpublish]

  def new
    @deal = Deal.new
    @deal.locations.build
    @deal.deal_images.build
  end

  def create
    @deal = Deal.new(deal_params)
    if @deal.save
      redirect_to admin_url, alert: "Deal successfully created."
    else
      render 'new'
    end
  end

  def update
    if @deal.update(deal_params)
      redirect_to admin_deal_path(@deal), notice: 'Deal was successfully updated.'
    else
      render :edit
    end

  end

  def index
    @deals = Deal.all
  end

  def publish
    @published = @deal.publish
    @errors_full_messages =  @deal.errors.full_messages
  end

  def unpublish
    @unpublished = @deal.unpublish
  end

  def destroy
    if @deal.destroy
      redirect_to admin_deals_path, notice: 'Deal was successfully deleted.'
    else
      redirect_to admin_url, alert: 'Fail to delete the Deal.'
    end
  end

  private

  def deal_params
    params.require(:deal).permit(:title, :description, :min_qty, :max_qty, :start_time, :expire_time, :price, :max_qty_per_customer, :instructions, :category_id, :merchant_id,
                                 locations_attributes: [:id, :address, :city, :state, :country, :_destroy],
                                 deal_images_attributes: [:id, :image, :_destroy]
                                 )
  end

  def set_deal
    @deal = Deal.find_by_id(params[:id])
    if @deal.nil?
      redirect_to admin_url, alert: "No such Deal exists."
    end
  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    @deals = Deal.live.paginate(page: params[:page])
  end

  def past
    @deals = Deal.past.paginate(page: params[:page])
  end

  def search
    @keyword = params[:search]
    @deals = Deal.search(@keyword).paginate(page: params[:page])
  end

  def refresh
    @deal = Deal.published.find_by(id: params[:id])
  end

  def show
    @deal = Deal.published.find_by(id: params[:id])
    if @deal.nil?
      redirect_to deals_path, alert: "No such Deal exists."
    end
  end

end

app/controllers/merchant/deals_controller.rb
class Merchant::DealsController < Merchant::BaseController

  def index
    @deals = current_merchant.deals.includes(:deal_images).published.paginate(page: params[:page], per_page: 10)
  end

  def show
    @deal = current_merchant.deals.published.find_by(id: params[:id])
    if @deal.nil?
      redirect_to merchant_deals_path, alert: "No such Deal exists."
    end
  end

end

app/helpers/admin/deals_helper.rb
module Admin::DealsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/merchant/deals_helper.rb
module Merchant::DealsHelper
end

app/views/deals/_deal.html.erb
<div class = "col-sm-6 col-md-3 deal_box">
   <div class = "thumbnail deal_thumbnail">
      <%= link_to deal_path(deal) do %>
      <%=image_tag deal.deal_images.first.image.url(:thumb), class: "img-responsive", alt: "deal.deal_images.first.image_file_name" %>
      <%end %>
   </div>
   
   <div class = "caption deal_caption">
      <h4><b><%= link_to deal.title, deal_path(deal) %></b></h4>
      <p><%= truncate(strip_tags(deal.description), length: 100)%></p>
   </div>
   <p>
      <% if deal.expired? %>
      <span class="label label-danger pull-right"> Expired </span>
      <% elsif deal.sold_out? %>
      <span class="label label-danger pull-right"> Sold</span>
      <% end %>
      <span class="label label-info pull-left large-font"><%= number_to_currency(deal.price, unit: "$") %></span>
   </p>
</div>

app/views/deals/index.html.erb
<div class="page-header col-md-offset-5">
<h2> Live Deals </h2>
</div>  
<hr>
<div class = "row">
<%= render @deals %>
</div>
<div class="page-footer col-md-offset-5">
<%= will_paginate @deals %>
</div>

app/views/deals/past.html.erb
<div class="page-header col-md-offset-5">
<h2> Past Deals </h2>
</div>  
<hr>
<div class = "row">
<%= render @deals %>   
</div>
<div class="page-footer col-md-offset-5">
<%= will_paginate @deals %>
</div>

app/views/deals/search.html.erb
<div class="page-header">
<h2> Search Results for '<%= @keyword %>'... </h2>
</div>  
<hr>
<div class = "row">
  <%= render @deals %>
</div>
<div class="page-footer col-md-offset-5">
<%= will_paginate @deals %>
</div>

app/views/deals/show.html.erb
<% content_for :head do %>
<%= javascript_include_tag 'slideshow' %>
<% end %>
<%= javascript_include_tag 'polling' %>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="thumbnail">
        <div class="center-block" data-behaviour = 'slideshow'>
          <%= render partial: 'deal_images/slideshow_deal_image', collection: @deal.deal_images %>
        </div>
        <div class="caption-full">
          <h4 class="pull-right"><%= number_to_currency(@deal.price, unit: "$") %></h4>
          <h3><%= @deal.title %></h3>
          <%= link_to deals_merchant_path(@deal.merchant) do %>
          <p class="lead text-success"> by <%= @deal.merchant.name %></p>
          <% end %>
          <hr>
          <p><b> Maximum Quantities : </b><%= @deal.max_qty %></p>
          <p><b> Maximum Quantity Per Customer : </b><%= @deal.max_qty_per_customer %></p>
          <p><b> Minimum Quantity Required to Redeem : </b><%= @deal.min_qty %></p>
          <hr>
          <p><b> Description : </b><%= simple_format( @deal.description ) %></p>
          <hr>
          <p><b> Instructions : </b><%= simple_format( @deal.instructions ) %></p>
        </div>
      </div>
    </div>
    <% #FIXME_AB: you should pass object to url helpers not id. read about to_param method -%>
    <div class="col-md-3" data-behaviour = "count-container" data-url="<%= refresh_deal_path(@deal) %>">
      <% if @deal.expired? %>
        <h3> <span class="label label-danger"> Deal Expired </span></h3>
      <% elsif @deal.sold_out? %>
        <h3 class= "text-center"> <span class="label label-danger"> Sold Out </span></h3>
      <% elsif @deal.live? %>
        <% if current_user && current_user.qty_can_be_purchased(@deal) <= 0 %>
          <h3 class= "text-center"> <span class="btn btn-info disabled"> Buy </span></h3>
          <h5> <b> Limit Reached of max. quantity per customer. </b> </h5>
        <% else %>
          <h3 data-behaviour = 'deal-status'><%= link_to 'Buy', new_deal_order_path(@deal), class: "btn btn-info" %></h3>
        <% end %>
        <h5 data-behaviour = 'remaining-quantity' > <b> Quantity Remaining </b> <span data-behaviour = 'quantity-remaining'> <%= @deal.quantity_available %> </span></h5>
        <h5 data-behaviour = 'sold-quantity' > <b> Quantity Sold </b> <span data-behaviour = 'quantity-sold'> <%= @deal.sold_quantity %> </span></h5>
        <% if @deal.remaining_quantity_to_activate > 0 %>
          <h5> <b> Need </b> <%= @deal.remaining_quantity_to_activate %> <b> more quantitites to be sold to activate the deal. </b></h5>
        <% end %>
      <% end %>
    </div>
  </div>
</div>