config/routes.rb
Rails.application.routes.draw do
  get '/activation/:token', to: 'users#account_activation', as: 'account_activation'
  get '/password_reset/:token', to: 'password_resets#new', as: 'reset_password'
  get '/merchant', to: 'merchant/coupons#new'

  post "/subscribe" => "subscriptions#create"

  resource :password_reset, only: [:create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :merchant_sessions, only: [:new, :create, :destroy]
  resource :password_request, only: [:new, :create]

  root 'deals#index'

  get "/signup", to: 'users#new'

  resource :users, only: [:create]

  resources :deals, only: [:index, :show] do
    collection do
      get 'search'
      get 'past'
    end
    member do
      get 'refresh'
    end
    resources :orders, only: [:new, :index, :edit, :update, :destroy, :show]
  end

  resources :merchants, only: [] do
    member do
      get 'deals'
    end
  end

  resources :categories, only: [] do
    member do
      get 'deals'
    end
  end

  get 'admin' => 'admin#index'

  namespace :api, defaults: { format: :json } do
    get '/orders/:token', to: 'orders#show'
  end

  namespace :merchant do
    resources :coupons, only: [:new] do
      collection do
        post 'redeem'
      end
    end
    resources :deals, only: [:index, :show]
  end

  namespace :admin do
    resources :deals do
      member do
        put 'publish'
        put 'unpublish'
      end
    end
    resources :reports, only: [] do
      collection do
        get 'merchants'
      end
    end
  end

  resources :orders do
    resources :charges, only: [:create]
  end

end

app/controllers/merchant_sessions_controller.rb
class MerchantSessionsController < Merchant::BaseController

  before_action :ensure_merchant, except: [:destroy]

  def new
  end

  def create
    merchant = Merchant.where(email: params[:email]).first
    if merchant && merchant.authenticate(params[:password])
      session[:merchant_id] = merchant.id
      redirect_to new_merchant_coupon_path
    else
      flash.now[:alert] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Logged out"
  end

  private

  def ensure_merchant
    if current_merchant
      flash[:notice] = "Your are not allowed to access this page."
      redirect_to root_url
    end
  end

end

app/helpers/merchant_sessions_helper.rb
module MerchantSessionsHelper
end

app/views/merchant_sessions/new.html.erb
<div class = 'row' >
  <div class = "well col-lg-6 col-lg-offset-2">
    <%= form_tag(merchant_sessions_path, method: :post, class: 'form-horizontal') do %>
    <fieldset>
      <legend class="text-center">Please Log In</legend>
      <div class="form-group">
        <%= label_tag :email, 'Email:', class: 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= email_field_tag :email, params[:email], class: 'form-control', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag :password, 'Password:', class: 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= password_field_tag :password, params[:password], class: 'form-control', required: true%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= submit_tag "Login", class: 'btn btn-primary' %>
        </div>
      </div>
    </fieldset>
    <% end %>
  </div>
</div>